### PR TITLE
Add capability to sort the listcomponent

### PR DESCRIPTION
**Pull request by sunayna**

### CODE REVIEW

**Comment by abhideep** [comment]
Please don't add that to the ListComponent. Either pass in a sorted list to it or create a SortedDataSource

**Comment by sunayna** [comment]
what is the harm in doing it this way?

**Comment by abhideep** [comment]
The ListComponent interface now keeps changing to be aware of all possible variations of it, in this case the sorter. For example, the SectionedListComponent is the only one that is aware of the grouping / sections in the list. 

Perhaps we can push this thru in the interest of speed, but add a TODO that this methodology needs to change.

**Comment by abhideep** [comment]
Do you still want me to look at this or is this ready to be merged in?

**Pull request closed without merging**
